-- CÂLINE — Données initiales (catégories + produits)
-- À exécuter APRÈS caline-schema.sql

-- Catégories ----------------------------------------------------------------
insert into categories(universe,slug,name,sort_order) values ('chien','alimentation','Alimentation',0) on conflict (universe,slug) do nothing;
insert into categories(universe,slug,name,sort_order) values ('chien','friandises','Friandises',1) on conflict (universe,slug) do nothing;
insert into categories(universe,slug,name,sort_order) values ('chien','jouets','Jouets',2) on conflict (universe,slug) do nothing;
insert into categories(universe,slug,name,sort_order) values ('chien','colliers','Colliers & Laisses',3) on conflict (universe,slug) do nothing;
insert into categories(universe,slug,name,sort_order) values ('chien','lits','Lits & Coussins',4) on conflict (universe,slug) do nothing;
insert into categories(universe,slug,name,sort_order) values ('chien','hygiene','Hygiène & Soins',5) on conflict (universe,slug) do nothing;
insert into categories(universe,slug,name,sort_order) values ('chat','jouets','Jouets',0) on conflict (universe,slug) do nothing;
insert into categories(universe,slug,name,sort_order) values ('chat','colliers','Colliers & Laisses',1) on conflict (universe,slug) do nothing;
insert into categories(universe,slug,name,sort_order) values ('chat','arbres','Arbres à chat',2) on conflict (universe,slug) do nothing;
insert into categories(universe,slug,name,sort_order) values ('chat','litiere','Litière & Accessoires',3) on conflict (universe,slug) do nothing;
insert into categories(universe,slug,name,sort_order) values ('chat','couchages','Couchages',4) on conflict (universe,slug) do nothing;
insert into categories(universe,slug,name,sort_order) values ('chat','hygiene','Hygiène & Soins',5) on conflict (universe,slug) do nothing;

-- Produits ------------------------------------------------------------------
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (3,'jouet-dinosaure-sonore-pour-chien-3','Jouet Dinosaure Sonore pour Chien','Peluche dinosaure couineuse, tissu résistant · 30 cm','Le compagnon de jeu préféré de votre chien. Ce dinosaure en velours côtelé cache un couineur qui réagit à chaque morsure : de quoi captiver votre chien pendant des heures. Sa texture gaufrée et résistante invite à mordiller, secouer et rapporter, tout en étant agréable à attraper. Un jouet ludique et robuste qui occupe votre compagnon et apaise son besoin de mâchouiller.',17.5,null,0,(select id from categories where universe='chien' and slug='jouets'),5,true,true,false,false,'["Orange","Vert","Marron"]'::jsonb,'{"Orange":1,"Vert":2,"Marron":3}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["Couineur intégré qui réagit à la morsure","Velours côtelé résistant et agréable","Format généreux d’environ 30 cm","Parfait pour mordiller et rapporter","Plusieurs coloris disponibles"]'::jsonb,'["Occupe et amuse votre chien","Satisfait l’instinct de mâchouille","Réduit l’ennui et le stress","Idéal pour les jeux de rapport","Solide pour un usage quotidien"]'::jsonb,'[["Le couineur est-il solide ?","Oui, il est logé à l’intérieur du jouet pour résister aux jeux énergiques."],["Convient-il aux gros mordeurs ?","Il résiste à un usage normal ; pour les mâcheurs très puissants, surveillez le jeu."],["Peut-on le laver ?","Oui, un lavage à la main à basse température est recommandé."],["Quelle est sa taille ?","Le dinosaure mesure environ 30 cm de haut pour 20 cm de large."]]'::jsonb,'["images/img121.jpg","images/img122.jpg","images/img123.jpg","images/img124.jpg","images/img125.jpg","images/img126.jpg"]'::jsonb,'videos/dino-chien.mp4',true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (9,'litiere-autonettoyante-intelligente-9','Litière Autonettoyante Intelligente','Litière autonettoyante, silencieuse et sans odeurs','La fin de la corvée de la litière. Cette litière autonettoyante intelligente se nettoie entièrement seule après chaque passage, sans aucune intervention de votre part. Son fonctionnement silencieux (moins de 40 dB) et ses capteurs anti-pincement assurent confort et sécurité à votre chat, tandis que son design moderne et épuré s’intègre à tous les intérieurs. Un quotidien plus propre, plus sain et sans odeurs.',299,null,0,(select id from categories where universe='chat' and slug='litiere'),5,true,true,false,false,'[]'::jsonb,'{}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["Nettoyage complet automatique, sans intervention","Fonctionnement silencieux (moins de 40 dB)","Capteurs anti-pincement pour la sécurité du chat","Sans odeurs, hygiène au quotidien","Design moderne et élégant"]'::jsonb,'["Fini la corvée de la litière","Un intérieur toujours propre et sans odeur","Sécurité maximale pour votre chat","Plus de tranquillité au quotidien","S’intègre à tous les intérieurs"]'::jsonb,'[["Le nettoyage est-il vraiment automatique ?","Oui, la litière se nettoie entièrement seule après chaque passage, sans aucune intervention."],["Est-elle silencieuse ?","Oui, son fonctionnement reste sous 40 dB, idéal pour un intérieur calme."],["Est-elle sûre pour mon chat ?","Des capteurs anti-pincement détectent la présence du chat et stoppent le mécanisme pour une sécurité maximale."],["Comment l’installer ?","Placez-la sur une surface plane, avec le tapis fourni devant l’appareil et sans obstacle à moins de 30 cm sur les côtés."]]'::jsonb,'["images/img94.jpg","images/img95.jpg","images/img96.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (11,'canne-a-plumes-interactive-11','Canne à Plumes Interactive','Oiseau à plumes à ventouse, avec grelot','L’instinct de chasse, même quand vous n’êtes pas là. Cet oiseau à vraies plumes, muni d’un petit grelot, se fixe au sol ou au mur grâce à sa ventouse et son fil souple : il rebondit et virevolte au moindre coup de patte, déclenchant des heures de jeu en autonomie. Un jouet léger et stimulant qui éveille l’énergie de votre chat tout en l’amusant.',14.93,null,0,(select id from categories where universe='chat' and slug='jouets'),5,true,true,false,false,'[]'::jsonb,'{}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["Oiseau en vraies plumes avec grelot","Ventouse + fil souple ultra-résistant","Mouvement rebondissant qui imite une proie","Jeu en autonomie, sans vous","Léger et facile à installer partout"]'::jsonb,'["Stimule l’instinct de chasse","Occupe votre chat seul","Dépense l’énergie et réduit l’ennui","Se fixe en un instant","Des heures de jeu garanties"]'::jsonb,'[["Comment se fixe-t-il ?","Grâce à une ventouse robuste qui se pose sur toute surface lisse (sol, mur, vitre)."],["Le grelot est-il bruyant ?","Non, c’est un léger tintement qui attire l’attention du chat sans déranger."],["Mon chat peut-il jouer seul ?","Oui, le fil souple rebondit à chaque coup de patte pour un jeu en totale autonomie."],["Les plumes résistent-elles ?","Les plumes sont solidement fixées ; surveillez néanmoins le jeu pour un usage prolongé."]]'::jsonb,'["images/img107.jpg","images/img108.jpg","images/img109.jpg","images/img110.jpg","images/img111.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (12,'arbre-a-chat-tour-lounge-12','Arbre à Chat Tour Lounge','Grande tour multi-niveaux : niches, hamac et griffoirs','Un véritable terrain de jeu pour votre chat. Cette grande tour multi-niveaux réunit perchoirs rembourrés, niches douillettes, hamac suspendu et poteaux en sisal naturel à griffer à volonté. Vos compagnons grimpent, se cachent, jouent et se reposent en hauteur, tout en préservant vos meubles. Stable et robuste, elle accueille même plusieurs chats à la fois.',125.69,null,0,(select id from categories where universe='chat' and slug='arbres'),5,true,true,false,false,'["Gris clair","Anthracite","Beige","Halloween","Noël"]'::jsonb,'{"Gris clair":1,"Anthracite":2,"Beige":3,"Halloween":4,"Noël":5}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["Plusieurs niveaux : perchoirs, niches et hamac","Poteaux en sisal naturel pour les griffes","Plateformes et niches rembourrées tout confort","Jouets suspendus pour stimuler le jeu","Structure stable et robuste"]'::jsonb,'["Préserve vos meubles des griffures","Espace de jeu, de repos et d’observation","Idéale pour un ou plusieurs chats","Réduit l’ennui et le stress","Un meuble félin élégant"]'::jsonb,'[["La tour est-elle stable ?","Oui, sa base large et ses poteaux renforcés assurent une bonne stabilité, même pour les chats actifs."],["Le montage est-il difficile ?","Le montage est simple et guidé ; visserie et notice incluses."],["Convient-elle aux grands chats ?","Oui, les plateformes et niches sont dimensionnées pour les chats de toutes tailles."],["Comment l’entretenir ?","Un brossage régulier et un coup d’aspirateur suffisent à garder le revêtement propre."]]'::jsonb,'["images/img93.jpg","images/img86.jpg","images/img87.jpg","images/img88.jpg","images/img89.jpg","images/img90.jpg","images/img91.jpg","images/img92.jpg"]'::jsonb,'videos/arbre-chat.mp4',true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (16,'coussin-ultra-doux-pour-chat-16','Coussin Ultra Doux pour Chat','Tapis réversible en peluche, doux et chaud','Un nid de douceur pour votre chat. Ce coussin réversible en peluche ultra-douce offre une surface moelleuse et chaleureuse où votre compagnon adore se lover. Léger et facile à déplacer, il se pose au sol, dans un panier ou une caisse de transport, et se lave sans effort. Disponible dans plusieurs imprimés tout doux, il apporte confort et réconfort à votre chat, jour après jour.',29.99,null,0,(select id from categories where universe='chat' and slug='couchages'),5,true,true,false,true,'["Bleu marine","Gris","Rose"]'::jsonb,'{"Bleu marine":0,"Gris":1,"Rose":2}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["Peluche ultra-douce, deux faces","Chaud et moelleux en toute saison","Léger, se pose et se déplace partout","Lavable en machine","Plusieurs imprimés adorables"]'::jsonb,'["Un couchage tout en douceur","Réconforte et apaise votre chat","S’adapte à tous les espaces","Facile à entretenir","Chaleur cocooning au quotidien"]'::jsonb,'[["Est-il lavable ?","Oui, il passe en machine à basse température et sèche rapidement."],["Convient-il aussi aux petits chiens ?","Oui, il convient parfaitement aux chats comme aux petits chiens."],["Les deux faces sont-elles utilisables ?","Oui, le coussin est réversible : une face imprimée et une face peluche unie."],["Quelles tailles / imprimés ?","Plusieurs imprimés sont disponibles ; choisissez votre coloris préféré au moment de l’achat."]]'::jsonb,'["images/img117.jpg","images/img118.jpg","images/img119.jpg","images/img120.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (17,'caline-cocoon-paw-17','CÂLINE Cocoon Paw™','Lit apaisant premium pour chiens','Un cocon de douceur pour un sommeil profond
Conçu pour rassurer et apaiser votre compagnon, ce lit enveloppant crée un véritable sentiment de sécurité qui favorise un repos plus calme et plus réparateur.
Sa forme inspirée d’une patte, son rembourrage généreux et sa texture ultra-douce offrent un confort exceptionnel au quotidien.',69.99,null,0,(select id from categories where universe='chien' and slug='lits'),5,true,true,false,true,'["Gris","Marron","Rose"]'::jsonb,'{"Gris":2,"Marron":3,"Rose":4}'::jsonb,'["S · 50cm","M · 60cm","L · 70cm","XL · 90cm"]'::jsonb,'[["S","50 cm","jusqu’à 5 kg"],["M","60 cm","5 à 12 kg"],["L","70 cm","12 à 25 kg"],["XL","90 cm","25 kg et plus"]]'::jsonb,'[]'::jsonb,'["Effet cocon rassurant","Ultra-moelleux et confortable","Base antidérapante","Lavable en machine","Adapté aux chiots comme aux chiens adultes"]'::jsonb,'["Sensation de sécurité","Réduction du stress","Chaleur et confort au quotidien","Soutien du corps pendant le sommeil","Repos plus profond et plus réparateur"]'::jsonb,'[["Le lit est-il lavable ?","Oui, il peut être lavé en machine à basse température."],["Convient-il aux grands chiens ?","Oui, plusieurs tailles sont disponibles pour s’adapter à différentes morphologies."],["Le fond glisse-t-il sur le sol ?","Non, la base est conçue pour rester stable grâce à son revêtement antidérapant."]]'::jsonb,'["images/img04.jpg","images/img05.jpg","images/img06.jpg","images/img07.jpg","images/img08.jpg","images/img09.jpg","images/img10.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (18,'lit-canape-moelleux-pour-chats-et-chiens-de-toutes-tailles-18','Lit Canapé Moelleux pour Chats et Chiens de Toutes Tailles','Nid douillet en fausse fourrure','Un nid douillet en fausse fourrure ultra-douce, au rebord surélevé qui enveloppe et rassure votre compagnon. Garnissage premium très moelleux, doublure coton soyeuse et fond antidérapant déperlant. Pour chats comme pour chiens, lavable en machine.',39.99,null,0,(select id from categories where universe='chien' and slug='lits'),5,true,true,false,true,'["Gris clair","Crème","Rose","Brun","Anthracite","Arc-en-ciel","Vert"]'::jsonb,'{"Gris clair":3,"Crème":4,"Rose":5,"Brun":6,"Anthracite":7,"Arc-en-ciel":8,"Vert":9}'::jsonb,'["S · 40cm (≤4 kg)","M · 50cm (≤7,5 kg)","L · 60cm (≤12,5 kg)"]'::jsonb,'[["S","40 cm","jusqu’à 4 kg"],["M","50 cm","jusqu’à 7,5 kg"],["L","60 cm","jusqu’à 12,5 kg"]]'::jsonb,'[]'::jsonb,'["Rebord surélevé enveloppant","Fausse fourrure ultra-douce","Fond antidérapant déperlant","Lavable en machine","Pour chats et chiens"]'::jsonb,'["Sensation de sécurité","Apaise l’anxiété","Chaleur et douceur","Soutien du sommeil","Repos réparateur"]'::jsonb,'[["Le lit est-il lavable ?","Oui, en machine à basse température."],["Convient-il aux chats et aux chiens ?","Oui, il convient aux deux, du chaton au chien moyen."],["Le fond glisse-t-il ?","Non, le fond antidérapant déperlant assure une bonne stabilité."]]'::jsonb,'["images/img11.jpg","images/img12.jpg","images/img13.jpg","images/img14.jpg","images/img15.jpg","images/img16.jpg","images/img17.jpg","images/img18.jpg","images/img19.jpg","images/img20.jpg"]'::jsonb,'videos/lit-canape.mp4',true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (19,'lit-canape-premium-pour-chien-et-chat-confort-douillet-toute-l-annee-19','Lit Canapé Premium pour Chien et Chat – Confort Douillet Toute l’Année','Matelas double épaisseur, quatre saisons','Un lit-canapé rectangulaire au rembourrage double épaisseur en coton PP haute résilience : moelleux, profond et enveloppant. Rebord surélevé qui soutient la tête, tissu doux résistant et fond antidérapant. Quatre saisons, confortable toute l’année. Pour chien comme pour chat.',34.99,null,0,(select id from categories where universe='chien' and slug='lits'),5,true,true,false,true,'["Rose","Gris","Vert","Taupe"]'::jsonb,'{"Rose":3,"Gris":4,"Vert":5,"Taupe":6}'::jsonb,'["S · 40×30cm (≤1,5 kg)","M · 50×38cm (≤3 kg)","L · 70×50cm (≤10 kg)","XL · 90×60cm (≤15 kg)","XXL · 110×70cm (≤25 kg)"]'::jsonb,'[["S","40 × 30 cm","≤ 1,5 kg"],["M","50 × 38 cm","≤ 3 kg"],["L","70 × 50 cm","≤ 10 kg"],["XL","90 × 60 cm","≤ 15 kg"],["XXL","110 × 70 cm","≤ 25 kg"]]'::jsonb,'[]'::jsonb,'["Rembourrage double épaisseur","Rebord qui soutient la tête","Tissu doux et résistant","Fond antidérapant","Déhoussable et lavable"]'::jsonb,'["Confort quatre saisons","Soutien des articulations","Sécurité et chaleur","Sommeil profond","Apaise le stress"]'::jsonb,'[["Le coussin est-il déhoussable ?","Oui, la housse se retire et se lave en machine."],["Convient-il aux grands chiens ?","Oui, la taille XXL accueille les chiens jusqu’à 25 kg."],["Le fond glisse-t-il ?","Non, la base antidérapante reste stable au sol."]]'::jsonb,'["images/img21.jpg","images/img22.jpg","images/img23.jpg","images/img24.jpg","images/img25.jpg","images/img26.jpg","images/img27.jpg","images/img28.jpg","images/img29.jpg"]'::jsonb,'videos/lit-canape-premium.mp4',true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (20,'lit-confort-ultra-moelleux-pour-animaux-4-coloris-au-choix-20','Lit Confort Ultra Moelleux pour Animaux – 4 Coloris au Choix','Imprimé fleuri, rebord rembourré','Un lit ovale ultra-moelleux au joli imprimé fleuri, avec rebord rembourré qui enveloppe et rassure votre compagnon. Garnissage gonflant, intérieur tout doux et housse aux motifs délicats. Confort quatre saisons, pour chiens comme pour chats. Disponible en 4 coloris.',29.99,null,0,(select id from categories where universe='chien' and slug='lits'),5,true,true,false,true,'["Violet","Rose","Vert","Bleu ciel"]'::jsonb,'{"Violet":2,"Rose":1,"Vert":3,"Bleu ciel":4}'::jsonb,'["S · 45×35cm (≤1,5 kg)","M · 55×45cm (≤7,5 kg)","L · 75×55cm (≤15 kg)"]'::jsonb,'[["S","45 × 35 cm","jusqu’à 1,5 kg"],["M","55 × 45 cm","jusqu’à 7,5 kg"],["L","75 × 55 cm","jusqu’à 15 kg"]]'::jsonb,'[]'::jsonb,'["Rebord rembourré enveloppant","Imprimé fleuri délicat","Intérieur tout doux","Confort quatre saisons","Pour chiens et chats"]'::jsonb,'["Sensation de sécurité","Apaise l’anxiété","Chaleur et douceur","Soutien du sommeil","Repos réparateur"]'::jsonb,'[["Le lit est-il lavable ?","Oui, en machine à basse température."],["Convient-il aux chats ?","Oui, il convient aux chats comme aux chiens."],["Y a-t-il plusieurs coloris ?","Oui, 4 coloris : Violet, Rose, Vert et Bleu ciel."]]'::jsonb,'["images/img30.jpg","images/img31.jpg","images/img32.jpg","images/img33.jpg","images/img34.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
Une délicatesse inhabituelle pour vos manipulateurs de viande Pet-Mersjo.
Ces friandises délicieuses et saines qui traiteront votre chien à un véritable état de délice.
Nos tresses de viande Mersjo sont fabriquées à partir de viande de haute qualité (plus de 85% de viande), qui a été séchées en douceur, pour maintenir ses saveurs naturelles et des qualités nutritionnelles.
Le poids du paquet est de 500 g, qui permetrai votre animal de compagnie pour profiter de plus.Les manipulateurs de viande Mersjo conviennent aux chiens de toutes races et de tailles.
En plus, nos délices sont riches en protéines et nutriments, qui sont importantes pour la croissance et le développement sains de votre chien.Sans l’ajout de chimie, de conservateurs et de couleurs artificielles.Vous pouvez être sure que vous le entregue uniquement le meilleur!
Les manipulateurs de viande de Mersjo!-dames de votre chien un régal, il ne peut pas résister!
Emballage : 500g
Instructions d’alimentation : nourrir entre les repas comme régal ou récompense comme partie d’une alimentation équilibrée.Soyez sûr de supervise le chien à tous les temps pendant l’alimentation.
Composition : produits pour viandes et animaux (contenu de viande à 85 %, comprenant 9,5% de repas de canard), produits d’origine végétale, huiles et graisses, minéraux.
Composants analytiques : protéine 48,8%, graisse 9,6%, Frêne 0,84%, fibre brute 1,6%, humidité 21%.',9.08,null,9.44,(select id from categories where universe='chien' and slug='friandises'),5,true,true,false,false,'[]'::jsonb,'{}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["images/img54.jpg","images/img55.jpg","images/img56.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
Quand vous achetez des friandises naturelles MERSJO, vous êtes assuré d’un déteste pour les friandises les plus saines pour votre chien, pour l’élimination et comme complément à une régime saine.
Haute teneur en viande (92%)
Pas de céréales ajoutées, sucre, rehausseurs de saveurs, rehausseurs
Processus de préparation délicat, qui grâce aux méthodes de séchage spéciales, vous permet de préserver tous les composants naturels et nutritionnels les plus importants
Un excellent complément pour la régime quotidienne
Ils satisfont le besoin naturel de mâcher
Excellent goût et texture : bouchées douces naturelles parfaites pour les animaux de petite et grande taille
100% NATUREL
MERSJO est une délicatesse du segment premium dépourvue de céréales, avec une viande de qualité.
COMPOSITION :
Poulet : 92%
Amidon de maïs : 3%
Protéines de pois : 3%
Glycérine : 2%
INGRÉDIENTS ANALYTIQUES :
Protéine brute : 30%
Graisse brute : 3%
Fibre brute : 2,5%
Cendres brutes : 2,5%
Humidité : 24%
Paquet : 1kg avec fermeture à ficelle pour garder le produit frais jusqu’au dernier régal.
Notes logistiques importantes !
Nous n’expédions pas vers : Îles Canaries, Tenerife.',23.49,null,9.44,(select id from categories where universe='chien' and slug='friandises'),5,true,true,false,false,'[]'::jsonb,'{}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["images/img57.jpg","images/img58.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
Des friandises naturelles MERSJO, parmi les plus saines pour votre chien : idéales en récompense et en complément d’une alimentation équilibrée.
Haute teneur en viande (87%)
Sans céréales ajoutées, sans sucre, sans exhausteurs de goût
Séchage doux qui préserve les saveurs et les qualités nutritionnelles
Excellent complément de l’alimentation quotidienne
Satisfont le besoin naturel de mâcher
Goût et texture parfaits : bouchées tendres pour petits et grands chiens
100% NATUREL
Pourquoi le canard ? Une viande facilement digestible, souvent recommandée pour les chiens au système digestif sensible. Riche en protéines de bonne digestibilité, pauvre en acides gras saturés, et source de vitamines B, de phosphore et de potassium.
COMPOSITION :
Canard : 67%
Morue : 20%
Farine de riz : 5%
Amidon de maïs : 2%
Protéines végétales : 4%
Glycérine : 2%
INGRÉDIENTS ANALYTIQUES :
Protéine brute : 13%
Graisse brute : 3,5%
Fibre brute : 2%
Cendres brutes : 2,5%
Humidité : 18%
Paquet : 500g avec fermeture à ficelle pour garder le produit frais jusqu’au dernier régal.
Note logistique : nous n’expédions pas vers les Îles Canaries et Tenerife.',11.19,null,9.44,(select id from categories where universe='chien' and slug='friandises'),5,true,true,false,false,'[]'::jsonb,'{}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["images/img59.jpg","images/img60.jpg","images/img61.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (28,'fontaine-pureflow-pour-chat-28','Fontaine PureFlow™ pour Chat','Fontaine à eau en acier inoxydable 304','Une hydratation pure, pour une vie plus saine
La fontaine PureFlow™ offre à votre chat une eau fraîche, filtrée et oxygénée en continu, qui l’encourage à boire davantage. Sa filtration multi-couches élimine impuretés, chlore et odeurs, tandis que sa pompe ultra-silencieuse (moins de 25 dB) fonctionne presque sans bruit. Réservoir en acier inoxydable 304 : hygiénique, durable et facile à nettoyer. Dimensions : 20,8 × 20,8 × 12 cm.',69.9,null,0,(select id from categories where universe='chat' and slug='hygiene'),5,true,true,false,true,'[]'::jsonb,'{}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["Eau filtrée, propre et saine","Ultra silencieuse (< 25 dB)","Circulation continue oxygénée","Acier inoxydable 304 hygiénique","Pompe à faible consommation"]'::jsonb,'["Encourage à boire davantage","Prévient la déshydratation","Soutient la santé rénale et urinaire","Eau fraîche en continu","Entretien simplifié"]'::jsonb,'[["La fontaine est-elle silencieuse ?","Oui, sa pompe fonctionne à moins de 25 dB, presque sans bruit."],["En quel matériau est-elle fabriquée ?","En acier inoxydable 304 : hygiénique, durable et résistant à la corrosion."],["L’eau est-elle filtrée ?","Oui, une filtration multi-couches élimine impuretés, chlore et odeurs."],["L’entretien est-il facile ?","Oui, le nettoyage est simple et le filtre se remplace facilement."]]'::jsonb,'["images/img62.jpg","images/img63.jpg","images/img64.jpg","images/img65.jpg","images/img66.jpg","images/img67.jpg","images/img68.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (29,'brosse-vapeur-3-en-1-pour-chiens-29','Brosse Vapeur 3-en-1 pour Chiens','Brossage, vapeur et massage en un seul geste','Le toilettage version cocooning. Cette brosse vapeur diffuse une fine brume d’eau tiède qui humidifie le poil pour le démêler en douceur, capturer les poils morts et apaiser la peau. Ses picots souples en silicone massent et stimulent la circulation à chaque passage. Avec son réservoir intégré et sa recharge USB sans fil, elle rend le brossage facile, agréable et sans corvée. Idéale pour réduire la mue et garder un pelage doux et brillant.',24.63,null,0,(select id from categories where universe='chien' and slug='hygiene'),5,true,true,false,true,'["Blanc","Beige","Jaune","Vert"]'::jsonb,'{"Blanc":2,"Beige":0,"Jaune":5,"Vert":6}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["Vapeur fine qui démêle sans tirer","Picots souples en silicone, effet massant","Capture les poils morts et réduit la mue","Réservoir d’eau intégré","Rechargeable par USB, sans fil"]'::jsonb,'["Démêlage doux, sans douleur","Moins de poils dans la maison","Peau apaisée et mieux irriguée","Pelage doux et brillant","Un vrai moment de complicité"]'::jsonb,'[["La vapeur est-elle sans danger ?","Oui, c’est une fine brume d’eau tiède, douce pour la peau et le poil de votre compagnon."],["Comment se recharge-t-elle ?","Par câble USB. Une charge complète offre une longue autonomie."],["Convient-elle à tous les pelages ?","Oui, les picots en silicone s’adaptent aux poils courts comme longs."],["Faut-il remplir un réservoir ?","Oui, un petit réservoir intégré se remplit d’eau pour générer la vapeur."]]'::jsonb,'["images/img74.jpg","images/img75.jpg","images/img69.jpg","images/img70.jpg","images/img71.jpg","images/img72.jpg","images/img73.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (30,'collier-cuir-grave-30','Collier Cuir Gravé','Cuir véritable, plaque en laiton gravée à votre nom','Un collier en cuir véritable au charme intemporel, personnalisé à votre image. La plaque en laiton se grave au nom de votre compagnon et à votre numéro — fini les médailles qui s’entrechoquent. Doublure rembourrée pour un confort optimal, boucle et anneaux en laiton massif, et coutures soignées. Réglable et décliné en plusieurs coloris, il allie élégance, solidité et sécurité au quotidien.',16.63,null,0,(select id from categories where universe='chien' and slug='colliers'),5,true,true,false,false,'["Gris","Marron","Vert","Rouge","Rose","Violet"]'::jsonb,'{"Gris":5,"Marron":4,"Vert":3,"Rouge":2,"Rose":6,"Violet":7}'::jsonb,'["XS","S","M","L","XL"]'::jsonb,'[["XS","32 cm","18–27 cm"],["S","37 cm","23–32 cm"],["M","42 cm","28–37 cm"],["L","50 cm","35–45 cm"],["XL","60 cm","42–55 cm"]]'::jsonb,'["Taille","Longueur totale","Tour de cou"]'::jsonb,'["Cuir véritable, finition soignée","Plaque en laiton gravée (nom + téléphone)","Doublure rembourrée, douce au toucher","Boucle et anneaux en laiton massif","Réglable, 5 tailles du XS au XL"]'::jsonb,'["Identification discrète et élégante","Aucun tintement de médaille","Confort sans irritation","Solide et durable","Un style unique pour votre compagnon"]'::jsonb,'[["Comment se fait la gravure ?","Vous indiquez le nom et le numéro souhaités lors de la commande, ils sont gravés sur la plaque en laiton."],["Quelle taille choisir ?","Mesurez le tour de cou de votre chien et laissez l’espace de deux doigts, puis reportez-vous au guide des tailles."],["Le cuir est-il résistant ?","Oui, c’est du cuir véritable robuste, conçu pour un usage quotidien."],["Convient-il aux petits chiens ?","Oui, la taille XS convient aux petits gabarits (tour de cou 18–27 cm)."]]'::jsonb,'["images/img78.jpg","images/img79.jpg","images/img80.jpg","images/img81.jpg","images/img82.jpg","images/img83.jpg","images/img84.jpg","images/img85.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (31,'laisse-premium-reglable-pour-chat-31','Laisse Premium Réglable pour Chat','Harnais + laisse en maille respirante, réglable','Les balades en toute sérénité. Cet ensemble harnais + laisse en maille respirante épouse le corps de votre chat sans comprimer son cou : la pression est répartie sur le poitrail pour un confort optimal. Réglable et anti-fugue, il sécurise chaque sortie, tandis que sa maille aérée reste légère et agréable à porter. Laisse assortie incluse, dans une belle palette de coloris.',19.99,null,0,(select id from categories where universe='chat' and slug='colliers'),5,true,true,false,false,'["Rose vif","Noir","Vert","Rouge","Bleu ciel","Orange","Rose","Violet"]'::jsonb,'{"Rose vif":2,"Noir":3,"Vert":4,"Rouge":5,"Bleu ciel":6,"Orange":7,"Rose":8,"Violet":9}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["Maille respirante, légère et aérée","Réglable pour un ajustement parfait","Conception anti-fugue, ferme et sécurisée","Laisse assortie incluse","Écusson patte décoratif, plusieurs coloris"]'::jsonb,'["Des sorties en toute sécurité","Ne blesse pas le cou de votre chat","Confortable, même porté longtemps","Facile à mettre et à retirer","Un style assorti pour chaque chat"]'::jsonb,'[["Comment choisir la taille ?","Mesurez le tour de poitrail de votre chat ; les sangles réglables permettent un ajustement précis."],["Mon chat peut-il s’échapper ?","Bien ajusté, le harnais répartit la pression et reste sécurisé pour éviter les fugues."],["Convient-il aux chatons ?","Oui, grâce à son réglage, il s’adapte aussi bien aux chatons qu’aux chats adultes."],["Est-il lavable ?","Oui, la maille se nettoie facilement à la main et sèche rapidement."]]'::jsonb,'["images/img97.jpg","images/img98.jpg","images/img99.jpg","images/img100.jpg","images/img101.jpg","images/img102.jpg","images/img103.jpg","images/img104.jpg","images/img105.jpg","images/img106.jpg"]'::jsonb,null,true,50) on conflict (legacy_id) do nothing;
insert into products(legacy_id,slug,name,subtitle,description,price,old_price,shipping,category_id,rating,is_best,is_new,is_promo,is_wellness,colors,color_images,sizes,size_guide,size_guide_head,pros,benefits,faq,images,video,in_stock,stock) values (32,'hamac-fenetre-premium-pour-chat-32','Hamac Fenêtre Premium pour Chat','Hamac à ventouses pour fenêtre · 45 × 30 cm','Le poste d’observation préféré de votre chat. Ce hamac se fixe directement à la fenêtre grâce à de puissantes ventouses : votre chat profite du soleil et observe l’extérieur, confortablement installé en hauteur. Disponible en maille respirante pour l’été ou en peluche douce pour l’hiver, il supporte le poids de votre compagnon et s’installe en quelques secondes, sans outil ni trou. Une place douillette qui ne prend aucune place au sol.',35.34,null,0,(select id from categories where universe='chat' and slug='couchages'),5,true,true,false,false,'["Beige","Gris","Peluche grise"]'::jsonb,'{"Beige":1,"Gris":2,"Peluche grise":3}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["Ventouses robustes, fixation sûre","Maille respirante ou peluche douce","Vue sur l’extérieur + bain de soleil","Supporte le poids du chat","Installation sans outil, gain de place"]'::jsonb,'["Un poste d’observation en hauteur","Des siestes au soleil bien méritées","Libère de l’espace au sol","Apaise et occupe votre chat","Se déplace où vous voulez"]'::jsonb,'[["Les ventouses tiennent-elles bien ?","Oui, sur une vitre propre et lisse, les ventouses offrent une excellente adhérence. Nettoyez la surface avant la pose."],["Quel poids supporte-t-il ?","Il est conçu pour accueillir confortablement la plupart des chats ; répartissez bien les ventouses."],["La housse est-elle lavable ?","Oui, la housse se retire et se lave facilement pour rester toujours propre."],["Quelle est la taille ?","La surface mesure environ 45 × 30 cm, idéale pour s’allonger pleinement."]]'::jsonb,'["images/img112.jpg","images/img113.jpg","images/img114.jpg","images/img115.jpg","images/img116.jpg"]'::jsonb,'videos/hamac-fenetre.mp4',true,50) on conflict (legacy_id) do nothing;
